import os
import urllib.parse
from prettyconf import config

VERSION="0.0.1"

EMAIL_ACCOUNT_USERNAME=config('EMAIL_ACCOUNT_USERNAME')
EMAIL_ACCOUNT_PASSWORD=config('EMAIL_ACCOUNT_PASSWORD')
EMAIL_PRIMARY_SMTP_ADDRESS=config('EMAIL_PRIMARY_SMTP_ADDRESS')